### ISSUE TITLE
Microsoft Computer Vision API key found in source

### ISSUE THREAD

**Issue by johnbindel** [Gravicode/APACAzureIoTDemo#1]
https://github.com/Gravicode/APACAzureIoTDemo/blob/c4d8641ae4bdf2ebd9aef622a40d89a881229fd5/IoT.Makers.Demo/SmartDemo/ComputerVisions/Program.cs

Since the key is checked into public github, _anyone can see/use it_. Consider taking the following steps to remedy this:
1. get a new API key (Azure Portal -> Cognitive Services -> Resource Management (Keys) -> Regenerate)
2. retire usage of key
3. do this with config that is not-version controlled- don't check the new key(s) into GitHub

**Comment by mifmasterz** [comment]
okay ;) thanks for your advice
